{% set name = "outlines" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/outlines-{{ version }}.tar.gz
  sha256: 8f7dcb055a99ba945c86982eb3675c9816d67e5af221ff07b09379d557b91ed6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - transformers ==4.36.2
    - python >=3.8
    - interegular
    - jinja2
    - lark
    - nest-asyncio
    - numpy
    - cloudpickle
    - diskcache
    - pydantic >=2.0
    - scipy
    - pytorch >=2.1
    - numba
    - joblib
    - referencing
    - jsonschema
    - requests

test:
  imports:
    - outlines
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/outlines-dev/outlines
  doc_url: https://outlines-dev.github.io/outlines
  summary: Probabilistic Generative Model Programming
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
