{% set name = "outlines" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/outlines-{{ version }}.tar.gz
  sha256: e731e788dcffe6aacd673af8a49df0807e85dc87f8eebeb51cf36b3a7eaaec59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - airportsdata
    - outlines-core ==0.1.14
    - typing_extensions
    - typing-extensions
    - datasets
    - pyairports
    - pycountry
    - tqdm
    - transformers
    - python >=3.8
    - interegular
    - jinja2
    - lark
    - nest-asyncio
    - numpy <2.0.0
    - cloudpickle
    - diskcache
    - pydantic >=2.0
    - scipy
    - pytorch
    - numba
    - joblib
    - referencing
    - jsonschema
    - requests

test:
  imports:
    - outlines
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/outlines-dev/outlines
  doc_url: https://outlines-dev.github.io/outlines
  summary: Probabilistic Generative Model Programming
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
